# The following patch adds labels advertising that this resource implements known
# duck types.
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    duck.knative.dev/podspecable: "true"
  name: podintents.conventions.carto.run
